import { expect, test } from '@playwright/test'

test('genera una señal determinista y la conserva sin duplicados', async ({ page }, testInfo) => {
  const email = process.env.E2E_EMAIL
  const password = process.env.E2E_PASSWORD
  if (!email || !password) throw new Error('E2E_EMAIL y E2E_PASSWORD son obligatorias')
  await page.goto('/login')
  await page.getByLabel('Correo electrónico').fill(email)
  await page.getByLabel('Contraseña').fill(password)
  await page.getByRole('button', { name: 'Entrar', exact: true }).click()
  await expect(page).toHaveURL('/')
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
  await page.getByRole('button', { name: 'Señales', exact: true }).click()
  const response = page.waitForResponse(r => r.url().endsWith('/api/v1/signals/generate') && r.request().method() === 'POST' && (r.request().postDataJSON() as { date?: string } | null)?.date === '2001-01-02')
  await page.getByLabel('Fecha de destino').fill('2001-01-02')
  expect((await response).status()).toBe(200)
  const card = page.getByRole('article', { name: 'Señal P02', exact: true })
  await expect(card).toHaveCount(1)
  await expect(card.getByText('07', { exact: true })).toBeVisible()
  await expect(card.getByText('Quiniela Leidsa', { exact: true })).toBeVisible()
  await expect(card.getByText('97 + 10 mod 100 = 07')).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('signals.png'), fullPage: true })
  await expect(page).toHaveURL(/date=2001-01-02/)
  await page.reload()
  await expect(page.getByLabel('Fecha de destino')).toHaveValue('2001-01-02')
  await expect(card).toHaveCount(1)
  await page.getByRole('button', { name: 'Generar señales', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('existentes')
  await expect(card).toHaveCount(1)
  await page.getByRole('button', { name: 'Métodos', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'P01', exact: true })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'A10', exact: true })).toBeVisible()
  expect(errors).toEqual([])
})
