import { FlaskConical, Layers3 } from 'lucide-react'
import { Badge } from '@/components/ui/badge'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { HealthStatus } from '@/features/health/HealthStatus'
import { AppShell } from '@/shared/layout/AppShell'

const futureModules = ['Señales', 'Métodos', 'Capital', 'Backtesting', 'Palés']

export function DashboardPage() {
  return <AppShell><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 sm:py-12"><section className="mb-10 grid gap-6 lg:grid-cols-[1fr_auto] lg:items-end"><div><Badge className="mb-4" variant="outline">Fase 0 completada</Badge><h1 className="max-w-3xl font-heading text-4xl leading-none font-semibold tracking-[-0.035em] sm:text-6xl">Infraestructura visible.<br /><em className="font-normal text-primary">Decisiones trazables.</em></h1><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">Este panel confirma que la base está lista. Todavía no calcula resultados, señales ni estrategias.</p></div><div className="flex items-center gap-3 rounded-xl border bg-card px-4 py-3"><span className="relative flex size-3"><span className="absolute inline-flex size-full animate-ping rounded-full bg-emerald-500 opacity-50" /><span className="relative inline-flex size-3 rounded-full bg-emerald-600" /></span><div><p className="text-sm font-semibold">Supervisión activa</p><p className="text-xs text-muted-foreground">Actualiza cada 30 segundos</p></div></div></section><section aria-labelledby="services-heading"><div className="mb-4 flex items-center gap-2"><Layers3 className="size-5 text-primary" aria-hidden="true" /><h2 id="services-heading" className="font-heading text-2xl font-semibold">Estado de servicios</h2></div><HealthStatus /></section><section className="mt-10" aria-labelledby="modules-heading"><Card className="border-dashed bg-card/60"><CardHeader><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-xl bg-accent"><FlaskConical aria-hidden="true" /></span><div><CardTitle id="modules-heading" className="text-xl">Próximos módulos</CardTitle><CardDescription>Visibles para marcar el alcance; deshabilitados hasta sus fases correspondientes.</CardDescription></div></div></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{futureModules.map((module) => <button key={module} type="button" disabled className="min-h-11 rounded-lg border bg-muted/50 px-4 text-left text-sm font-medium text-muted-foreground disabled:cursor-not-allowed">{module}<span className="mt-1 block font-mono text-[10px] uppercase tracking-wider">No disponible</span></button>)}</div></CardContent></Card></section></main></AppShell>
}
