import { RefreshCw } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { useManualSync, useRecentOperations, useSyncStatus } from '@/features/draws/api'
import { AppShell } from '@/shared/layout/AppShell'

export function DrawsPage() {
  const status = useSyncStatus()
  const sync = useManualSync()
  const operations = useRecentOperations()
  const data = status.data?.data
  const request = (ids?: number[]) => sync.mutate(ids, { onSuccess: () => toast.success('Sincronización encolada.'), onError: () => toast.error('No se pudo encolar la sincronización.') })
  if (status.isLoading) return <AppShell><main className="mx-auto max-w-7xl px-4 py-8">Cargando sorteos…</main></AppShell>
  if (status.isError || !data) return <AppShell><main className="mx-auto max-w-7xl px-4 py-8">No se pudo cargar el estado de sorteos.</main></AppShell>
  return <AppShell><main className="mx-auto max-w-7xl px-4 py-8 sm:px-6"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-muted-foreground">{data.local_date} · Provider: {data.provider}</p><h1 className="font-heading text-3xl font-semibold">Sorteos</h1><p className="text-sm text-muted-foreground">Automatización {data.automatic_sync_enabled ? 'activa' : 'desactivada'}</p></div><Button onClick={() => request()} disabled={sync.isPending}><RefreshCw className="mr-2 size-4" />Sincronizar todas</Button></div><div className="mb-6 grid gap-3 sm:grid-cols-3"><Card><CardHeader><CardTitle>Actualizadas</CardTitle></CardHeader><CardContent>{data.lotteries.filter((lottery) => lottery.status === 'updated').length}</CardContent></Card><Card><CardHeader><CardTitle>Errores</CardTitle></CardHeader><CardContent>{data.open_errors}</CardContent></Card><Card><CardHeader><CardTitle>Cuarentenas</CardTitle></CardHeader><CardContent>{data.open_quarantines}</CardContent></Card></div><section className="grid gap-3 md:grid-cols-2">{data.lotteries.map((lottery) => <Card key={lottery.id}><CardContent className="flex items-center justify-between gap-3 pt-6"><div><p className="font-medium">{lottery.name} <span className="text-muted-foreground">#{lottery.external_id}</span></p><p className="text-sm text-muted-foreground">{lottery.today_draw ? `${lottery.today_draw.p1} · ${lottery.today_draw.p2} · ${lottery.today_draw.p3}` : 'Pendiente'} · {lottery.status}</p></div><Button variant="outline" size="sm" onClick={() => request([lottery.external_id])} disabled={sync.isPending}>Sincronizar</Button></CardContent></Card>)}</section><section className="mt-8 grid gap-3 md:grid-cols-3"><Card><CardHeader><CardTitle>Ejecuciones recientes</CardTitle></CardHeader><CardContent>{operations.data?.[0].data.map((run) => <p key={run.uuid} className="text-sm">{run.status}</p>) ?? 'Sin ejecuciones'}</CardContent></Card><Card><CardHeader><CardTitle>Errores recientes</CardTitle></CardHeader><CardContent>{operations.data?.[1].data.map((error) => <p key={error.id} className="text-sm">{error.message}</p>) ?? 'Sin errores'}</CardContent></Card><Card><CardHeader><CardTitle>Cuarentenas recientes</CardTitle></CardHeader><CardContent>{operations.data?.[2].data.map((item) => <p key={item.id} className="text-sm">{item.error_code}</p>) ?? 'Sin cuarentenas'}</CardContent></Card></section></main></AppShell>
}
